version: '3.3'

services:
    db:
      image: mysql:5.7
      volumes:
        - db_data:/var/lib/mysql
      restart: always
      ports:
        - "3306:3306"
      networks:
        - wordpress_net
      environment:
        MYSQL_ROOT_PASSWORD: aw3se4dr5
        MYSQL_DATABASE: wordpress
        MYSQL_USER: wordpress
        MYSQL_PASSWORD: wordpress

    wordpress:
      depends_on:
        - db
      image: wordpress:latest
      volumes:
        - wordpress:/var/www/html
      ports:
        - "8000:80"
      networks:
        - wordpress_net
      depends_on:
      - db
      restart: always
      environment:
        WORDPRESS_DB_HOST: db:3306
        WORDPRESS_DB_USER: wordpress
        WORDPRESS_DB_PASSWORD: wordpress

volumes:
  db_data:
  wordpress:

networks:
    wordpress_net:
      driver: bridge
